version: 2
jobs:
  test:
    docker:
      - image: registry.dev.brainhub.pl/tools/rancher-circleci
        auth:
          username: $HARBOR_USER
          password: $HARBOR_PASSWORD
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $HARBOR_USER -p $HARBOR_PASSWORD registry.dev.brainhub.pl
      - run: docker build --build-arg NODE_ENV=development -t registry.dev.brainhub.pl/react-carousel/react-carousel .
      - run: docker run --rm --name react-carousel --entrypoint '/bin/sh' registry.dev.brainhub.pl/react-carousel/react-carousel -c 'npm run lint'
      - run: docker run --rm --name react-carousel --entrypoint '/bin/sh' registry.dev.brainhub.pl/react-carousel/react-carousel -c 'npm run test'

  build_and_deploy:
    docker:
      - image: registry.dev.brainhub.pl/tools/rancher-circleci
        auth:
          username: $HARBOR_USER
          password: $HARBOR_PASSWORD
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $HARBOR_USER -p $HARBOR_PASSWORD registry.dev.brainhub.pl
      - run: docker build -t registry.dev.brainhub.pl/react-carousel/react-carousel .
      - run: docker push registry.dev.brainhub.pl/react-carousel/react-carousel:latest
      - run: rancher-compose --project-name react-carousel --verbose up -d --force-upgrade --pull --confirm-upgrade react-carousel

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - build_and_deploy:
          requires:
            - test
          filters:
            branches:
              only: master
